### ISSUE TITLE
Getting error " InternalOAuthError: Failed to fetch user profile "

### ISSUE THREAD

**Issue by Illuri** [BrentAureli/Youtube-Tutorials#8]
When I tried to authenticate google using passport I am getting the following error. I used the same code which is in "Youtube-Tutorials/NodeJS Tutorials/Tutorial 11 - Google OAuth/"

InternalOAuthError: Failed to fetch user profile
    at E:\NodeJS_Ex\node_modules\passport-google-oauth20\lib\strategy.js:99:19
    at ClientRequest.<anonymous> (E:\NodeJS_Ex\node_modules\oauth\lib\oauth2.js:162:5)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at TLSSocket.socketErrorListener (_http_client.js:387:9)
    at emitOne (events.js:116:13)
    at TLSSocket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:66:8)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**Comment by gauravArora04** [comment]
Can anyone help with this ?
